### ISSUE TITLE
Gradle should build executable JAR

### ISSUE THREAD

**Issue by jbeorse** [opendatakit/skunkworks-parrot#19]
Gradle should be used for building the executable JAR artifact

**Comment by Saikat2019** [comment]
@jbeorse  can I start working on this?

**Comment by linl33** [comment]
Please go ahead and work on it.

**Comment by linl33** [comment]
@Saikat2019 Can you give us an update on this?

**Comment by Saikat2019** [comment]
@linl33 ... I was looking into the code,and as it already has a build.gradle to use Gradle I was trying to figure out how to ignore/remove the pom.xml so that we don't need maven .
 Currently I'm unable to work properly because of my health issue, doctor said I'll be fine within 4-5 days. I'll try to finish this issue after that. Sorry for the inconvenience.
        Regards Saikat.

**Comment by linl33** [comment]
That's fine. Hope you get well soon. 

Some clarification on the issue. 
The project as it is only needs Gradle. Maven is not needed and unsupported. 
The goal of the issue is to have Gradle produce an executable jar, which should
 1. Include a `Main-Class` entry in its `MANIFEST.MF`
 2. Include the dependencies 

This is sometimes known as a fat jar or an uber jar.

**Comment by Saikat2019** [comment]
@linl33 , I have done it , please review
